### PR TITLE
Add FLTO and Strip

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Add FLTO (Faster Binaries) and Strip (Smaller Binaries) to Nimporter using Nim built-in defines.
- 2 Lines Diff.

:)

### CODE REVIEW

**Comment by Pebaz** [comment]
Awesome! Thanks!

**Comment by Benjamin-Lee** [comment]
Nice work! Are these symbols defined here (https://github.com/nim-lang/Nim/pull/14013)? I've never seen them be passed as `-d:` options so that's super cool.

**Comment by juancarlospaco** [comment]
Yes they are builtin on Nim itself.

**Comment by Benjamin-Lee** [comment]
Sweet. Thanks for the PR! I couldn't find those flags defined anywhere in the docs so I'm impressed.

**Comment by juancarlospaco** [comment]
They live on the CFG of the compiler I think.

**Comment by Keithcat1** [comment]
I added those flags recently.
There's a known issue with Mack, but I've submitted a PR and it should get fixed eventually. I didn't think people would start using these flags quite so quickly, but then again, they do make quite a difference sometimes.

**Pull request merged**
