### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by juancarlospaco**
- CI Update.

### CODE REVIEW

**Comment by juancarlospaco** [comment]
@Pebaz See the error on Mac OS X, Ive seen it too on my packages, I do not understand the errors, any idea?. :thinking:

**Comment by juancarlospaco** [comment]
@Pebaz Ping.

See also https://stackoverflow.com/a/67432351

**Comment by Pebaz** [comment]
Hi @juancarlospaco thanks for pinging me I meant to look into this but it slipped my mind. I'll take a look over the weekend and see if I can find out anything.

**Comment by Pebaz** [comment]
After some more research, it looks like there are now two main versions of Nim:

* v1.4.6
* 1.2.12

As [noted here](https://nim-lang.org/blog/2021/04/15/versions-146-and-1212-released.html), Nim v1.4.6 is not compatible with Nim v.1.2.12, since Nimporter was recently using 1.0.6, this applies to the current MacOS build issue.

I believe that as far as I can tell (I tested 1.4.6, 1.4.4, 1.4.2), I believe that Nimporter is just not compatible with the latest version of Nim (v1.4.6).

They said in [this post](https://nim-lang.org/blog/2021/04/15/versions-146-and-1212-released.html) that this would happen as they introduced breaking changes on a minor version update, which means that usually this would require Nim to be updated to a `2.x.x` version, but instead they are just maintaining two different minor versions for existing users.

Increasingly recently, I have not had enough time to devote to Nimporter and would like to pass the torch to someone that could do a better job closing Issues and merging Pull Requests.

@juancarlospaco Would you be interested in becoming the main maintainer for Nimporter with full repository access so that the community can still benefit from some support for this library? In time, I hope that I can help out more but for right now I just can't devote the time necessary to make changes like the one described above about rearchitecting Nimporter to support this new Nim version change.

What do you think?

**Comment by Pebaz** [comment]
@juancarlospaco Regarding [this user's error](https://stackoverflow.com/questions/67431610/error-importing-faster-than-requests-on-windows/67432351#67432351), it has to do with an old Nimporter version that did not have a try/except block surrounding the error message construction. Updating Nimporter should do the trick.

**Comment by SekouDiaoNlp** [comment]
> Increasingly recently, I have not had enough time to devote to Nimporter and would like to pass the torch to someone that could do a better job closing Issues and merging Pull Requests.
> 
> @juancarlospaco Would you be interested in becoming the main maintainer for Nimporter with full repository access so that the community can still benefit from some support for this library? In time, I hope that I can help out more but for right now I just can't devote the time necessary to make changes like the one described above about rearchitecting Nimporter to support this new Nim version change.
> 
> What do you think?

Hi @Pebaz , I am a contributor to one of @juancarlospaco project, and I also am the creator and maintainer of my own Open Source projects. I am able to devote 8 to 10 hours a week to `Nimporter`. As I am a veteran Python developer, but pretty new at NIM (still know enough to compile and debug NIM code), It will be a great opportunity for me to enlarge a deepen my knowledge of NIM, while at the same time supporting an Open Source project that I myself use and find useful. It might also help lighten your burden of maintaining this project.

Let me know if you are interested.

@SekouDiaoNlp

**Comment by juancarlospaco** [comment]
BTW I changed `choosenim_install` to automatically install `nimpy` and `fusion` after installing `nim`, and is running CI.
https://github.com/juancarlospaco/choosenim_install
https://pypi.org/project/choosenim-install

Maybe in the future the logic to check for `nimpy` in nimporter can be removed ?.

**Comment by Pebaz** [comment]
@SekouDiaoNlp Thank you so much for the offer! I'd say if you're interested, let's do it!

Essentially the expectation here would be:

* Answering any basic questions/issues in the GitHub Issues page
* Merging any pull requests after vetting them locally or via the pipeline
* Looping me in for massive architectural changes (although I'm pretty much cool with whatever as long as simplicity is the main focus for the user experience)

If you're cool to move forward I'll add whatever permissions you need to be able to help out when you have time!

**Comment by SekouDiaoNlp** [comment]
Let's do it.

You can contact me privately yo organize all the stuff.

**Pull request closed without merging**
